### ISSUE TITLE
django models loading import cache

### ISSUE THREAD

**Issue by jjsdouglas** [alex/django-templatetag-sugar#14]
I'm trying to track down a caching error on my site and found this warning from the templatetag-sugar app.

...\lib\site-packages\templatetag_sugar\parser.py:4: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import cache

@alex 

I saw this potential fix
https://github.com/ottoyiu/django-cors-headers/issues/64

**Comment by loimu** [comment]
actually fix is here https://github.com/alex/django-templatetag-sugar/pull/13

**Comment by jjsdouglas** [comment]
Thanks @loimu
