### ISSUE TITLE
Ambiguous errors on improper tag syntax in template

### ISSUE THREAD

**Issue by unbracketed** [alex/django-templatetag-sugar#2]
Syntax checking could be improved during parsing since it is possible to get some ambiguous errors if a tag's syntax is not specified properly in a template. For example, taking the fairly canonical context-populating tag:

```
@tag(register,
 [Constant("for"), Variable(), Optional([Constant("as"), Name()])])
    def get_comments_for_article(context, article_id, varname=None):
        #...
```

If you attempt to reference the tag in a template via:

```
{% get_comments_for_article %}
```

the error is severe enough that you don't even get the Django 500 page.

**Comment by alex** [comment]
Fixed in b9ae4753056f38bcab4b
